name: takeda
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.10.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - bleach=6.2.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=2.2.1
  - expat=2.7.1
  - gettext=0.21.0
  - git=2.51.0
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - idna=3.7
  - ipykernel=6.30.1
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - ld_impl_linux-64=2.44
  - libcurl=8.15.0
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - openssl=3.0.18
  - overrides=7.4.0
  - packaging=25.0
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pcre2=10.46
  - perl=5.40.2
  - pexpect=4.9.0
  - pip=25.2
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - send2trash=1.8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.50.2
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - arrow==1.3.0
      - click==8.3.0
      - cmake==3.25.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - filelock==3.13.1
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - hf-xet==1.2.0
      - huggingface-hub==1.0.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jsonpointer==3.0.0
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyterlab==4.4.9
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.3.0
      - lit==15.0.7
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.3
      - notebook==7.4.7
      - numpy==1.26.4
      - nvidia-ml-py==13.580.82
      - nvitop==1.5.3
      - openpyxl==3.1.5
      - pandas==2.3.3
      - pillow==11.0.0
      - pyparsing==3.2.5
      - pytz==2025.2
      - rfc3987-syntax==1.1.0
      - safetensors==0.6.2
      - shellingham==1.5.4
      - sympy==1.13.3
      - thop==0.1.1-2209072238
      - timm==1.0.21
      - torch==2.0.1+cu117
      - torchaudio==2.0.2+cu117
      - torchvision==0.15.2+cu117
      - tqdm==4.67.1
      - triton==2.0.0
      - typer-slim==0.20.0
      - types-python-dateutil==2.9.0.20251008
      - tzdata==2025.2
      - uri-template==1.3.0
      - webcolors==24.11.1
      - widgetsnbextension==4.0.14
prefix: /home/fangq/.miniconda/envs/takeda
